name: cse151b_pa3
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl
  - pycocotools
  - pip:
    - torchviz
  - nltk
  